{
 "title": "Conference ICUFN2025 Dashboard",
 "time": { "from": "2025-07-09T06:00:00.000Z", "to": "2025-07-09T18:00:00.000Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Sensor",
    "label": "Sensor",
    "query": "from(bucket: \"ICUFNDB\")\r\n  |> range(start: 2023-11-20T11:00:00Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> distinct(column: \"sensor_name\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "General Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ICUFNDB\")\r\n  |> range(start: 2025-07-03T16:35:00Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> last()\r\n  |> group(columns: [])\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> filter(fn: (r) => r[\"sensor_name\"] != \"B332\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      sensor_status: if (uint(v: now()) - uint(v: r._time)) <= 600000000000 then \"Active\" else \"Inactive\"\r\n  }))"
    }
   ]
  },
  {
   "title": "CVTT Crowding Geodistribution",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "t1 = from(bucket: \"ICUFNDB\")\r\n  |> range(start: 2025-07-03T15:35:10Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorLocation\" )\r\n  |> drop(columns:[\"_start\", \"_stop\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()\r\n\r\n\r\nt2 = from(bucket: \"ICUFNDB\")\r\n  |> range(start: 2025-07-03T16:35:00Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> last()\r\n  |> group(columns: [])\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n\r\n\r\njoin( tables: {Locations: t1, Detections: t2}, on: [\"sensor_name\"])\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> last(column: \"sensor_name\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Last Records (30 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"ICUFNDB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devices_detected\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] != \"B332\")\r\n  |> filter(fn: (r) => contains(value: r[\"sensor_name\"], set: ${Sensor:json}))\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: int(v: math.round(x: r._value)), _time:r._time, _field:r.sensor_name}))"
    }
   ]
  },
  {
   "title": "CVTT Heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"ICUFNDB\")\r\n  |> range(start: 2025-07-03T15:35:10Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> filter(fn: (r) => contains(value: r[\"sensor_name\"], set: ${Sensor:json}))\r\n  |> drop(columns:[\"_start\", \"_stop\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Last Records (5 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"ICUFNDB\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devices_detected\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] != \"B332\")\r\n  |> filter(fn: (r) => contains(value: r[\"sensor_name\"], set: ${Sensor:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  //|> movingAverage(n: 3)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.sensor_name}))"
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}