{
 "title": "Palacio Galveias Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "influxdb" },
   { "name": "Bucket", "query": "buckets()" },
   {
    "name": "Sensor",
    "label": "Sensor",
    "query": {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> distinct(column: \"sensor_name\")\r\n  |> group()"
    }
   }
  ]
 },
 "panels": [
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"\n  width: 100%;\n  padding: px 24px;\n  font-family: 'Inter', 'Segoe UI', Roboto, sans-serif;\n\">\n  <div style=\"\n    font-size: 40px;\n    font-weight: 600;\n    color: #263238;\n    letter-spacing: 0.4px;\n  \">\n  Palácio Galveias\n"
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devices_detected\")\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"sensor_name\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Geodistribution",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "t1 = from(bucket: \"${Bucket}\")\r\n  |> range(start: 2025-07-03T15:35:10Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorLocation\" )\r\n  |> last(column: \"sensor_name\")\r\n  |> drop(columns:[\"_start\", \"_stop\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()\r\n\r\nt2 = from(bucket: \"${Bucket}\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> drop(columns:[\"_start\", \"_stop\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> last(column: \"devices_detected\")\r\n  |> group()\r\n\r\n\r\njoin( tables: {Locations: t1, Detections: t2}, on: [\"sensor_name\"])\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> last(column: \"devices_detected\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "5 min. detections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devices_detected\")\r\n  |> filter(fn: (r) => contains(value: r[\"sensor_name\"], set: ${Sensor:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> exponentialMovingAverage(n: 7)\r\n  |> map(fn: (r) => ({_value: math.round(x: r._value), _time: r._time, _field: r.sensor_name}))"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: 2025-08-20T09:35:10Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> filter(fn: (r) => contains(value: r[\"sensor_name\"], set: ${Sensor:json}))\r\n  |> aggregateWindow(every: 60m, fn: mean, createEmpty: false)\r\n  |> drop(columns:[\"_start\", \"_stop\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "30 min. average detections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"math\"\r\nfrom(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"numdetections\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"devices_detected\")\r\n  //|> filter(fn: (r) => contains(value: r[\"sensor_name\"], set: ${Sensor:json}))\r\n  |> aggregateWindow(every: 30m, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: r._value,\r\n      sensor_name: r.sensor_name\r\n    }))\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> yield(name: \"result\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: 2025-07-03T16:35:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"numdetections\" and r.sensor_name != \"NewSensor1\")\r\n  |> group(columns: [\"sensor_name\"])\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      _value:\r\n        if (uint(v: now()) - uint(v: r._time)) <= 600000000000\r\n        then \"Active\"\r\n        else \"Inactive\",\r\n      sensor_name: r.sensor_name\r\n  }))\r\n"
    }
   ]
  }
 ]
}