
# TELEGRAF – CHIRPSTACK 

[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"
  flush_jitter = "0s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = true
  debug = true



# NUMDETECTIONS (C,xx)

[[inputs.mqtt_consumer]]
  name_override = "numdetections"
  servers = ["${HELIUM_MQTT_URL}"]
  topics = ["${HELIUM_COUNT_TOPIC}"]

  username = "${HELIUM_MQTT_USER}"
  password = "${HELIUM_MQTT_PASSWORD}"

  data_format = "json_v2"

  [inputs.mqtt_consumer.tags]
    source     = "helium"
    technology = "lorawan"

  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.tag]]
      path   = "deviceInfo.deviceName"
      rename = "device_id"

    [[inputs.mqtt_consumer.json_v2.field]]
      path   = "object.count"
      rename = "count"
    
    [[inputs.mqtt_consumer.json_v2.field]]
      path   = "object.norm_new_fingerprints"
      rename = "norm_new_fingerprints"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path   = "object.norm_disappeared_fingerprints"
      rename = "norm_disappeared_fingerprints"
      optional = true



# SENSOR LOCATION (latitude + longitude)

[[inputs.mqtt_consumer]]
  name_override = "sensorLocation"
  servers = ["${HELIUM_MQTT_URL}"]
  topics = ["${HELIUM_LOCATION_TOPIC}"]

  username = "${HELIUM_MQTT_USER}"
  password = "${HELIUM_MQTT_PASSWORD}"

  data_format = "json_v2"

  [inputs.mqtt_consumer.tags]
    source     = "helium"
    technology = "lorawan"

  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.tag]]
      path   = "deviceInfo.deviceName"
      rename = "device_id"

    [[inputs.mqtt_consumer.json_v2.field]]
      path   = "object.latitude"
      rename = "lat"

    [[inputs.mqtt_consumer.json_v2.field]]
      path   = "object.longitude"
      rename = "lon"


# Device ID fallback via topic

[[processors.regex]]
  tagpass = { source = ["helium"] }

  [[processors.regex.tags]]
    key         = "mqtt_topic"
    pattern     = "chirpstack/uplink/([^/]+)/"
    replacement = "${1}"
    result_key  = "device_id"


# Bucket Router via PostgreSQL

[[processors.execd]]
  tagpass = { source = ["helium"] }
  command = ["/usr/local/bin/pg_router_execd.py"]
  environment = ["PG_DSN=${PG_DSN}"]



[[outputs.influxdb_v2]]
  tagpass = { source = ["helium"] }

  urls = ["${INFLUX_URL}"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_DEFAULT_BUCKET}"
  bucket_tag   = "bucket"
  exclude_bucket_tag = true
