# =========================
# Telegraf (TTN -> Influx)
# =========================

[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"
  flush_jitter = "0s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = true
  debug = true

[[inputs.mqtt_consumer]]
  name_override = "ttn_uplink"
  servers   = ["ssl://eu1.cloud.thethings.network:8883"]
  topics    = ["v3/${TTN_APPLICATION_ID}/devices/+/up"]
  username  = "${TTN_USERNAME}"
  password  = "${TTN_API_KEY}"
  qos       = 0
  client_id = "telegraf-ttn-uplink"
  data_format = "json"
  json_query  = "uplink_message.decoded_payload"
  tag_keys = ["type"]
  topic_tag = "mqtt_topic"

  [inputs.mqtt_consumer.tags]
    technology = "lorawan"

[[processors.regex]]
  tagpass = { technology = ["lorawan"] }
  [[processors.regex.tags]]
    key         = "mqtt_topic"
    pattern     = "v3/[^/]+/devices/([^/]+)/up"
    replacement = "${1}"
    result_key  = "device_id"

[[processors.starlark]]
  tagpass = { technology = ["lorawan"] }
  script = "/etc/telegraf/scripts/set_measurement.star"

[[processors.execd]]
  tagpass = { technology = ["lorawan"] }
  command = ["/usr/local/bin/influx_bucket_router.py"]
  environment = [
    "PG_DSN=${PG_DSN}"
  ]

[[outputs.influxdb_v2]]
  tagpass = { technology = ["lorawan"] }
  urls         = ["${INFLUX_URL}"]
  token        = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket       = "Bucket_Default"
  bucket_tag   = "bucket"
  exclude_bucket_tag = true